### ISSUE TITLE
Link to NU Hacks Discord server

### ISSUE THREAD

**Issue by KarlFish** [hacks/hacks.github.io#48]
The website should provide a permanent invite to the official NU Hacks Discord server:

 [https://discord.gg/AEt3Kp4](https://discord.gg/AEt3Kp4)

**Comment by ctbeiser** [comment]
it should not.

I'm out of the loop, so it's not clear to me if this is actually an "Official" discord—mods pls—but when I dropped in and looked around, I saw racist memes, people calling eachother "fags", and honestly like

in 2018, this is a bad aesthetic, it is not what hacks is about, what are you even doing here. why does this seem like a good idea.

**Comment by aliceyoung9** [comment]
Hard agree.

This discord server has no business being linked on the webpage (or, tbh having NU Hacks in the name) unless a Hacks officer is actively moderating this. Especially if y'all are tacitly condoning racist and homophobic memes.

Take out the trash.

**Comment by KarlFish** [comment]
Got it. I was basing this off of posters like the following. I didn't realize the server wasn't official.

![nu_hacks_poster](https://user-images.githubusercontent.com/12851254/37110223-4ee28aec-220a-11e8-8fba-1659f1a6a345.png)

**Comment by edward-shen** [comment]
If I may give my two cents, I agree with @erikuhlmann. I've been on this server since it's creation and AFAICR the server has never condoned racist or homophobic messages. I would appreciate seeing an example, with context, of the things he was talking about.

**Comment by aliceyoung9** [comment]
While we're all here:

# Shit I found on the Discord server that shouldn't have happened, period
* Using the word "trap" to describe trans women, ever
* Using the word "trap" to describe your fellow Northeastern students who are trans
* Talking about seeing a particular Northeastern student's genitals.

# Shit that certainly shouldn't be on the "NUHacks Discord Server" (as referenced in the initial Github Issue and the NUHacks poster) 
* Using the word "trap" to describe trans women, ever
* Using the word "trap" to describe your fellow Northeastern students who are trans
* Talking about seeing a particular Northeastern student's genitals.

Do y'all need screenshots to refresh your memory?

**Comment by ssssssssssssssssssk** [comment]
Many of these complaints are being taken wildly out of context. Oftentimes **the victims of the offensive jokes made were also the perpetrators**. For example, Master Yeezy makes many Jew and gay jokes but she's also Jewish and gay (bi). It's no more offensive than an African-American referring to someone else with the n-word.

---

I (キラ) would also like to preface this next section by stating that I am a pansexual trans woman. To the extent of my knowledge, the following statements are true and correct:
* The word "trap" was never used to describe trans women. The usage of "trap" in subject Discord describes individuals who 1) identify as male, 2) have a penis, and 3) present as female.
* No talk of seeing a particular Northeastern student's genitals occurred in subject Discord. Please provide a memory refresher.

While I certainly do not represent all trans women or all gays (LGBTQ+ individuals), my own opinion is that the **Discord was neither transphobic nor homophobic**.

---

@aliceyoung9 
@ali 
@ctbeiser

**Comment by aliceyoung9** [comment]
> Many of these complaints are being taken wildly out of context

What did y'all honestly expect would happen after someone suggested that this was the NUHacks Discord server? It doesn't matter how insular you thought this (public) Discord server was; a board member put the invite link on posters around campus. Plus there was this github issue that sent an email to every past officer who hadn't bothered to unsubscribe. Within the discussion, there are members asking if the Discord is the official Hacks channel, and then other members agreeing, without any board members disagreeing. The board should have considered what kind of impression the content in this channel would leave on a prospective member. Is Hacks now only for children who tolerate all the trash 4chan reposts y'all see fit to share?

The fact is that the NUHacks board is ultimately responsible for moderating the discussion channels it promotes, and Trey is either neglecting his responsibility as discord server admin and board member, or he's tacitly approving of the content. Because Hacks is (last I checked) a student organization, y'all risk losing recognition as a student org when you fail to ensure reasonable levels of inclusive conduct. Various current officers have already admitted in the separated email thread that the conduct in the server does not reflect org values. 

![img_0932](https://user-images.githubusercontent.com/2482343/37152672-299d1f06-22a8-11e8-8799-abc755665379.PNG)
![img_0934](https://user-images.githubusercontent.com/2482343/37152690-360b51e0-22a8-11e8-8a0e-069ff867fc35.jpg)
![img_0933](https://user-images.githubusercontent.com/2482343/37152703-3d775a00-22a8-11e8-9420-87f11bd90391.PNG)

What's blurred out is a name of someone who is indeed a Northeastern student.

With regards to the specific transphobic slur-- You do not get to singularly decide for a marginalized group that a slur is non-offensive and acceptable for people outside of that group to use. Especially when your attempts to define it do not address that the usage (search through the discord! There are soooooo many instances) implies that trans women aren't "real women" on account of the trans part....which...seems like textbook transphobia. @ssssssssssssssssssk What you (and others in the discord) personally decide to put up with is not what's up for discussion; it's about the kind of environment that this language creates for the student org.

**Comment by ssssssssssssssssssk** [comment]
Look, whatever Trey did with associating the Discord with NU Hacks is on him. I just refuse to let you cherrypick seemingly offensive remarks out of context and use them to unfairly call me and my friends transphobes and homophobes.

---

So with your first screencap, again, we are using the word "trap" as defined in my previous post. I have been in the server since its inception and I have never seen said word used as a slur. What you're doing is akin to asserting that the sentence "I bought some crackers today" contains a racial slur.

The usage of "trap" has only being used to describe trans women relatively recently, circa 2012 when the EEOC "made headlines across the nation as the first decision at the federal level which extended anti-discrimination protections to transgender people in the area of employment" ([source](https://transgenderlawcenter.org/archives/2773)). This was likely a form of backlash from transphobes. Correlation is drawn from the data below:

[![Google Trends](https://imgur.com/aOEKYp9)](https://trends.google.com/trends/explore?date=all&q=%22trap%22%20reddit,trans%20woman)

In other words, the term "trap" in and of itself has only ever been used to describe crossdressing cis men who pass for women. This was derived from an anime trope where effeminate and androgynous cis boys were often mistaken for girls. While there are other issues with this trope, I shall address only the ones pertaining to trans women for now. The usage of "trap" which you are referring to is that hijacked by alt-right trolls. Please, do not associate me or others with them. Personally, I think that the discussion around "traps" and whether they are "gay" or not is an effective way of getting people to think more deeply about what masculinity really is and how sexuality plays into all of that. Who knows, it might lead them to uproot toxic masculinity and heteronormativity somewhere down the line.

> You do not get to singularly decide for a marginalized group that a slur is non-offensive and acceptable for people outside of that group to use.

Yes, and you don't get to decide what is actually classified as that slur or not either. 

> implies that trans women aren't "real women" on account of the trans part....which...seems like textbook transphobia.

Yes, I know how "trap" can be used in transphobic ways, thank you for clarifying. Again, it has never been used in the same way that the alt-right transphobes have been using it.

---

**Note:** the last two screencaps, while having two different dates, are actually from the same conversation at the same time (discussion took place around midnight).

> What's blurred out is a name of someone who is indeed a Northeastern student.

Yes, it is the name of a Northeastern student. Yes, she's an openly trans girl. Kindly refer yourself back to the conversation and scroll up. Take the subject image and perform a reverse image search. You will find that the name of the character that the cosplayer is dressing up as also shares that name. **The blurred out name is in reference to the character, not the Northeastern student.**

As for the last complaint screencap, it is fairly common for traps (crossdressing cis males who pass as females) to cosplay as female characters from various media. In said screencap, a discussion was taking place for whether the cosplayer herself was a girl (including cis/trans) or a crossdressing cis male. **In fact, said screencap offers an example of an individual respecting trans women's identities.** In more coherent words, what "caseyp me" was saying was that there's no way a crossdressing cis male could pass that well without being on hormones, in which case any person AMAB being on hormones that long would most likely be a girl (a trans girl).

---

Thank you for your concern for marginalized groups. I believe that it is also important for student organizations to be as inclusive as possible. However, I would appreciate it if you didn't take conversations out of context to label people as transphobes and use them as scapegoats when your real issue is with Trey's moderation.

I would also like to note that almost no one except for Trey ever considered the Discord as something for NU Hacks. It was mostly just a gathering place for CS kiddos.

---

@aliceyoung9 
@ali 
@ctbeiser

**Comment by ctbeiser** [comment]
I'm not going to adjucate every single comment on this discord; this is but a small sliver, and besides that, much of the context we might want to disagree about is gone, since Trey decided to delete them.

I have been asked by the board to make this issue private, and edit or delete people's comments in order to make it not look as if they were affiliated. I'd be open to burying this thread if the people in it argued they were uncomfortable with their youthful indiscretions being publicized, but I haven't seen that yet.

I want to make clear that there was an affiliation until yesterday, which is why the board needed to vote to disaffiliate themselves, why the server had "NUHacks" in its name, and why it showed up on a poster that was attached to KarlFish's comment earlier in this thread, which, having been removed, I'm putting here. Commentary inside the discord seems to mirror this, and suggest that everyone involved was aware that something objectionable was happening: 
![ef32793b-1728-4df8-8417-e5fd45a74653](https://user-images.githubusercontent.com/614019/37166154-29dffad2-22b3-11e8-8fe5-7d90910e66cc.jpeg)
![05b7fb23-4b67-4023-8045-f2d35bdb6830](https://user-images.githubusercontent.com/614019/37166313-8d37f01c-22b3-11e8-8834-df78c5dd4289.jpeg)

**Comment by ssssssssssssssssssk** [comment]
I for one would like to move past this drama. I think everyone here can agree that the Discord being presented as affiliated with NU Hacks was not appropriate. Let’s leave it at that.

**Comment by edward-shen** [comment]
@ctbeiser I would also suggest locking this thread, to prevent people from discussing on this further. The original issue has already been well resolved at this point.

**Comment by KarlFish** [comment]
> it showed up on a poster that was attached to KarlFish's comment earlier in this thread, which, having been removed, I'm putting here

A member of the board privately requested that I remove associations 
to the discord server from my issue. The poster contains a permanent 
invite to the server and personally identifying information. Neither of these
are necessary.

Please use this image instead:

![blur](https://user-images.githubusercontent.com/12851254/37167832-04090718-22d1-11e8-9ca9-b0dbe69b62fc.png)

**Comment by treyzania** [comment]
@KarlFish I've since revoked the invite.

**Comment by ssssssssssssssssssk** [comment]
+1 for deleting all content in this thread

**Comment by KarlFish** [comment]
![blur](https://user-images.githubusercontent.com/12851254/37168568-46e4a9dc-22d3-11e8-9115-172828ef0c8c.png)

**Comment by molly** [comment]
@ssssssssssssssssssk "I for one would like to move past this drama. I think everyone here can agree that the Discord being presented as affiliated with NU Hacks was not appropriate. Let’s leave it at that."

I'm kind of boggled that the issue to you here is that this Discord was briefly affiliated with NUHacks and not that it exists in the first place.

Gay or not, calling folks fags can be wildly offensive. Regardless of whether folks are trans or crossdressing or what have you, [https://www.glaad.org/reference/transgender](trap) can be wildly offensive. The chats about gassing jews and images mentioning "glorious reichland" are wildly offensive. Trying to play these off as just gay folks being self-deferential, Jewish folks being self-deferential, etc. is completely absurd. I'm glad this won't be associated with Hacks, but seriously, consider your channel at all.

There are enough edgelords in CS already. Hacks used to be an awesome place where you could trust folks didn't hate you for being (a woman|gay|trans|Jewish|*) and it sucks to see that's not the case anymore.

**Comment by erikuhlmann** [comment]
There seems to be a lot of "policing" by Hacks alums going on for this issue. And as I see it, you all are being quite rude to @ssssssssssssssssssk, which seems a little ironic considering the issue at hand.

**Comment by molly** [comment]
@erikuhlmann Elaborate..?

**Comment by ssssssssssssssssssk** [comment]
Since y’all clearly lack reading comprehension skills, I’d like to reiterate my sentiments to **close and move past this topic**.

This whole drama has been stressful and emotionally draining on me and my friends, including the very people you are trying to protect. I should’ve listened to my boyfriend when he advised that I not waste my time on this circlejerk.

That being said, I’d like to advise that in the future, issues like this not be made public. Not only should allegations as serious as the ones brought up against our server members not be published online without sufficient evidence and high confidence, the affected parties should at least be given a chance to explain themselves. Instead, what we have here seems to be a misinformed lynch train that benefits no one.

**Comment by ssssssssssssssssssk** [comment]
If you have any followup questions or concerns, don’t hesitate to contact me at sssssssskthway@gmail.com.

I will deactivate this account and I strongly suggest that the rest of you refrain from exasterbating the problem either.

**Comment by molly** [comment]
I read pretty well actually... But this Discord channel was posted on printed Hacks flyers around campus and suggested to be added to the hacks.io website and so I think it's cool to discuss it a bit more thoroughly now that the conversation has been started, not just end all discussion when folks realized this was a terrible idea.

I would also advise your server members consider that they are posting in public Discord chats.

**Comment by molly** [comment]
Also cc @treyzania ?

**Comment by treyzania** [comment]
@molly Since this issue was originally raised we have addressed all of the complaints given.  We (the current board) appreciate the concern from Hacks alums, but this discussion here is far beyond constructive criticism.  None of the messages sent had a bigoted intention, and in-context were reasonable.  If you still have an issue, please take it up privately with the people in question.

The people who truly represent Hacks and are regular faces at meetings are some of the best and most accepting people I have met at Northeastern.  Quasi-anonymity brings out negatives in people, and the ease of access online allowed the inclusion of people that *aren't* regulars and aren't necessarily representatives of Hacks' culture.

**+1 for locking this thread**

**Comment by ctbeiser** [comment]
@treyzania When I posted these, I looked at the context, and none seemed particularly exculpatory, including around the map that you posted. If you believed they “in-context were reasonable,” I don’t understand why you felt the need to wipe the history of the server and remove that.

**Comment by ali** [comment]
IDK if the context really makes it any better TBH

![memes](https://user-images.githubusercontent.com/515861/37236610-67b93ace-23d7-11e8-9a8e-1b63516213cc.png)
